import 'package:hive/hive.dart';
import 'goal_model.dart';
import 'task_model.dart';
import 'habit_model.dart';
import 'time_block_model.dart';
import 'sub_goal_model.dart';
import 'user_behavior_model.dart';

// ==================== GoalModel Adapter ====================
class GoalModelAdapter extends TypeAdapter<GoalModel> {
  @override final int typeId = 0;
  @override
  GoalModel read(BinaryReader reader) {
    final n = reader.readByte();
    final f = <int, dynamic>{for (int i = 0; i < n; i++) reader.readByte(): reader.read()};
    return GoalModel(
      id: f[0] as String, titleEn: f[1] as String, titleAr: f[2] as String,
      descriptionEn: f[3] as String, descriptionAr: f[4] as String,
      deadline: f[5] as DateTime, priority: f[6] as int,
      progress: f[7] as double, category: f[8] as String,
      createdAt: f[9] as DateTime, isActive: f[10] as bool,
    );
  }
  @override
  void write(BinaryWriter writer, GoalModel obj) {
    writer..writeByte(11)
      ..writeByte(0)..write(obj.id)..writeByte(1)..write(obj.titleEn)
      ..writeByte(2)..write(obj.titleAr)..writeByte(3)..write(obj.descriptionEn)
      ..writeByte(4)..write(obj.descriptionAr)..writeByte(5)..write(obj.deadline)
      ..writeByte(6)..write(obj.priority)..writeByte(7)..write(obj.progress)
      ..writeByte(8)..write(obj.category)..writeByte(9)..write(obj.createdAt)
      ..writeByte(10)..write(obj.isActive);
  }
}

// ==================== TaskModel Adapter ====================
class TaskModelAdapter extends TypeAdapter<TaskModel> {
  @override final int typeId = 1;
  @override
  TaskModel read(BinaryReader reader) {
    final n = reader.readByte();
    final f = <int, dynamic>{for (int i = 0; i < n; i++) reader.readByte(): reader.read()};
    return TaskModel(
      id: f[0] as String, goalId: f[1] as String,
      titleEn: f[2] as String, titleAr: f[3] as String,
      durationMinutes: f[4] as int, priority: TaskPriority.values[f[5] as int],
      status: TaskStatus.values[f[6] as int],
      scheduledDate: f[7] as DateTime?, createdAt: f[8] as DateTime,
      isAutoGenerated: f[9] as bool,
    );
  }
  @override
  void write(BinaryWriter writer, TaskModel obj) {
    writer..writeByte(10)
      ..writeByte(0)..write(obj.id)..writeByte(1)..write(obj.goalId)
      ..writeByte(2)..write(obj.titleEn)..writeByte(3)..write(obj.titleAr)
      ..writeByte(4)..write(obj.durationMinutes)..writeByte(5)..write(obj.priorityIndex)
      ..writeByte(6)..write(obj.statusIndex)..writeByte(7)..write(obj.scheduledDate)
      ..writeByte(8)..write(obj.createdAt)..writeByte(9)..write(obj.isAutoGenerated);
  }
}

// ==================== HabitModel Adapter ====================
class HabitModelAdapter extends TypeAdapter<HabitModel> {
  @override final int typeId = 2;
  @override
  HabitModel read(BinaryReader reader) {
    final n = reader.readByte();
    final f = <int, dynamic>{for (int i = 0; i < n; i++) reader.readByte(): reader.read()};
    return HabitModel(
      id: f[0] as String, goalId: f[1] as String?,
      titleEn: f[2] as String, titleAr: f[3] as String,
      frequencyDays: f[4] as int, streak: f[5] as int,
      completionRate: f[6] as double, lastCompletedDate: f[7] as DateTime?,
      createdAt: f[8] as DateTime,
    );
  }
  @override
  void write(BinaryWriter writer, HabitModel obj) {
    writer..writeByte(9)
      ..writeByte(0)..write(obj.id)..writeByte(1)..write(obj.goalId)
      ..writeByte(2)..write(obj.titleEn)..writeByte(3)..write(obj.titleAr)
      ..writeByte(4)..write(obj.frequencyDays)..writeByte(5)..write(obj.streak)
      ..writeByte(6)..write(obj.completionRate)..writeByte(7)..write(obj.lastCompletedDate)
      ..writeByte(8)..write(obj.createdAt);
  }
}

// ==================== TimeBlockModel Adapter ====================
class TimeBlockModelAdapter extends TypeAdapter<TimeBlockModel> {
  @override final int typeId = 3;
  @override
  TimeBlockModel read(BinaryReader reader) {
    final n = reader.readByte();
    final f = <int, dynamic>{for (int i = 0; i < n; i++) reader.readByte(): reader.read()};
    return TimeBlockModel(
      id: f[0] as String, taskId: f[1] as String?,
      labelEn: f[2] as String, labelAr: f[3] as String,
      date: f[4] as DateTime, startHour: f[5] as int,
      startMinute: f[6] as int, endHour: f[7] as int,
      endMinute: f[8] as int, priorityColorIndex: f[9] as int,
      isCompleted: f[10] as bool, isFixed: f[11] as bool,
    );
  }
  @override
  void write(BinaryWriter writer, TimeBlockModel obj) {
    writer..writeByte(12)
      ..writeByte(0)..write(obj.id)..writeByte(1)..write(obj.taskId)
      ..writeByte(2)..write(obj.labelEn)..writeByte(3)..write(obj.labelAr)
      ..writeByte(4)..write(obj.date)..writeByte(5)..write(obj.startHour)
      ..writeByte(6)..write(obj.startMinute)..writeByte(7)..write(obj.endHour)
      ..writeByte(8)..write(obj.endMinute)..writeByte(9)..write(obj.priorityColorIndex)
      ..writeByte(10)..write(obj.isCompleted)..writeByte(11)..write(obj.isFixed);
  }
}

// ==================== SubGoalModel Adapter ====================
class SubGoalModelAdapter extends TypeAdapter<SubGoalModel> {
  @override final int typeId = 5;
  @override
  SubGoalModel read(BinaryReader reader) {
    final n = reader.readByte();
    final f = <int, dynamic>{for (int i = 0; i < n; i++) reader.readByte(): reader.read()};
    return SubGoalModel(
      id: f[0] as String, parentGoalId: f[1] as String,
      titleEn: f[2] as String, titleAr: f[3] as String,
      progress: f[4] as double, deadline: f[5] as DateTime,
      isCompleted: f[6] as bool, createdAt: f[7] as DateTime,
    );
  }
  @override
  void write(BinaryWriter writer, SubGoalModel obj) {
    writer..writeByte(8)
      ..writeByte(0)..write(obj.id)..writeByte(1)..write(obj.parentGoalId)
      ..writeByte(2)..write(obj.titleEn)..writeByte(3)..write(obj.titleAr)
      ..writeByte(4)..write(obj.progress)..writeByte(5)..write(obj.deadline)
      ..writeByte(6)..write(obj.isCompleted)..writeByte(7)..write(obj.createdAt);
  }
}

// ==================== UserBehaviorModel Adapter ====================
class UserBehaviorModelAdapter extends TypeAdapter<UserBehaviorModel> {
  @override final int typeId = 6;
  @override
  UserBehaviorModel read(BinaryReader reader) {
    final n = reader.readByte();
    final f = <int, dynamic>{for (int i = 0; i < n; i++) reader.readByte(): reader.read()};
    return UserBehaviorModel(
      id: f[0] as String, eventType: f[1] as String,
      relatedId: f[2] as String?, hour: f[3] as int,
      dayOfWeek: f[4] as int, category: f[5] as String,
      timestamp: f[6] as DateTime,
    );
  }
  @override
  void write(BinaryWriter writer, UserBehaviorModel obj) {
    writer..writeByte(7)
      ..writeByte(0)..write(obj.id)..writeByte(1)..write(obj.eventType)
      ..writeByte(2)..write(obj.relatedId)..writeByte(3)..write(obj.hour)
      ..writeByte(4)..write(obj.dayOfWeek)..writeByte(5)..write(obj.category)
      ..writeByte(6)..write(obj.timestamp);
  }
}
