// GENERATED CODE - Manually written Hive adapters
// In production, run: flutter packages pub run build_runner build

import 'package:hive/hive.dart';
import 'goal_model.dart';
import 'task_model.dart';
import 'habit_model.dart';
import 'time_block_model.dart';

// ==================== GoalModel Adapter ====================
class GoalModelAdapter extends TypeAdapter<GoalModel> {
  @override
  final int typeId = 0;

  @override
  GoalModel read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return GoalModel(
      id: fields[0] as String,
      titleEn: fields[1] as String,
      titleAr: fields[2] as String,
      descriptionEn: fields[3] as String,
      descriptionAr: fields[4] as String,
      deadline: fields[5] as DateTime,
      priority: fields[6] as int,
      progress: fields[7] as double,
      category: fields[8] as String,
      createdAt: fields[9] as DateTime,
      isActive: fields[10] as bool,
    );
  }

  @override
  void write(BinaryWriter writer, GoalModel obj) {
    writer
      ..writeByte(11)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.titleEn)
      ..writeByte(2)
      ..write(obj.titleAr)
      ..writeByte(3)
      ..write(obj.descriptionEn)
      ..writeByte(4)
      ..write(obj.descriptionAr)
      ..writeByte(5)
      ..write(obj.deadline)
      ..writeByte(6)
      ..write(obj.priority)
      ..writeByte(7)
      ..write(obj.progress)
      ..writeByte(8)
      ..write(obj.category)
      ..writeByte(9)
      ..write(obj.createdAt)
      ..writeByte(10)
      ..write(obj.isActive);
  }
}

// ==================== TaskModel Adapter ====================
class TaskModelAdapter extends TypeAdapter<TaskModel> {
  @override
  final int typeId = 1;

  @override
  TaskModel read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    final task = TaskModel(
      goalId: fields[1] as String,
      titleEn: fields[2] as String,
      titleAr: fields[3] as String,
      durationMinutes: fields[4] as int,
    );
    task.id = fields[0] as String;
    task.priorityIndex = fields[5] as int;
    task.statusIndex = fields[6] as int;
    task.scheduledDate = fields[7] as DateTime?;
    task.createdAt = fields[8] as DateTime;
    task.isAutoGenerated = fields[9] as bool;
    return task;
  }

  @override
  void write(BinaryWriter writer, TaskModel obj) {
    writer
      ..writeByte(10)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.goalId)
      ..writeByte(2)
      ..write(obj.titleEn)
      ..writeByte(3)
      ..write(obj.titleAr)
      ..writeByte(4)
      ..write(obj.durationMinutes)
      ..writeByte(5)
      ..write(obj.priorityIndex)
      ..writeByte(6)
      ..write(obj.statusIndex)
      ..writeByte(7)
      ..write(obj.scheduledDate)
      ..writeByte(8)
      ..write(obj.createdAt)
      ..writeByte(9)
      ..write(obj.isAutoGenerated);
  }
}

// ==================== HabitModel Adapter ====================
class HabitModelAdapter extends TypeAdapter<HabitModel> {
  @override
  final int typeId = 2;

  @override
  HabitModel read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return HabitModel(
      id: fields[0] as String,
      goalId: fields[1] as String,
      titleEn: fields[2] as String,
      titleAr: fields[3] as String,
      isDaily: fields[4] as bool,
      streak: fields[5] as int,
      completionDates: (fields[6] as List).cast<DateTime>(),
      createdAt: fields[7] as DateTime,
    );
  }

  @override
  void write(BinaryWriter writer, HabitModel obj) {
    writer
      ..writeByte(8)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.goalId)
      ..writeByte(2)
      ..write(obj.titleEn)
      ..writeByte(3)
      ..write(obj.titleAr)
      ..writeByte(4)
      ..write(obj.isDaily)
      ..writeByte(5)
      ..write(obj.streak)
      ..writeByte(6)
      ..write(obj.completionDates)
      ..writeByte(7)
      ..write(obj.createdAt);
  }
}

// ==================== TimeBlockModel Adapter ====================
class TimeBlockModelAdapter extends TypeAdapter<TimeBlockModel> {
  @override
  final int typeId = 3;

  @override
  TimeBlockModel read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return TimeBlockModel(
      id: fields[0] as String,
      taskId: fields[1] as String?,
      date: fields[2] as DateTime,
      startHour: fields[3] as int,
      startMinute: fields[4] as int,
      endHour: fields[5] as int,
      endMinute: fields[6] as int,
      priorityColorIndex: fields[7] as int,
      labelEn: fields[8] as String,
      labelAr: fields[9] as String,
      isCompleted: fields[10] as bool,
    );
  }

  @override
  void write(BinaryWriter writer, TimeBlockModel obj) {
    writer
      ..writeByte(11)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.taskId)
      ..writeByte(2)
      ..write(obj.date)
      ..writeByte(3)
      ..write(obj.startHour)
      ..writeByte(4)
      ..write(obj.startMinute)
      ..writeByte(5)
      ..write(obj.endHour)
      ..writeByte(6)
      ..write(obj.endMinute)
      ..writeByte(7)
      ..write(obj.priorityColorIndex)
      ..writeByte(8)
      ..write(obj.labelEn)
      ..writeByte(9)
      ..write(obj.labelAr)
      ..writeByte(10)
      ..write(obj.isCompleted);
  }
}
