import 'package:hive/hive.dart';
import 'package:uuid/uuid.dart';


enum TaskStatus { todo, inProgress, done }

enum TaskPriority { red, orange, yellow, green, gray }

@HiveType(typeId: 1)
class TaskModel extends HiveObject {
  @HiveField(0)
  late String id;

  @HiveField(1)
  late String goalId;

  @HiveField(2)
  late String titleEn;

  @HiveField(3)
  late String titleAr;

  @HiveField(4)
  late int durationMinutes;

  @HiveField(5)
  late int priorityIndex; // TaskPriority index

  @HiveField(6)
  late int statusIndex; // TaskStatus index

  @HiveField(7)
  late DateTime? scheduledDate;

  @HiveField(8)
  late DateTime createdAt;

  @HiveField(9)
  late bool isAutoGenerated;

  TaskModel({
    String? id,
    required this.goalId,
    required this.titleEn,
    required this.titleAr,
    required this.durationMinutes,
    TaskPriority priority = TaskPriority.yellow,
    TaskStatus status = TaskStatus.todo,
    this.scheduledDate,
    DateTime? createdAt,
    this.isAutoGenerated = false,
  }) {
    this.id = id ?? const Uuid().v4();
    priorityIndex = priority.index;
    statusIndex = status.index;
    this.createdAt = createdAt ?? DateTime.now();
  }

  TaskPriority get priority => TaskPriority.values[priorityIndex];
  TaskStatus get status => TaskStatus.values[statusIndex];

  set priority(TaskPriority p) => priorityIndex = p.index;
  set status(TaskStatus s) => statusIndex = s.index;

  String getTitle(String locale) => locale == 'ar' ? titleAr : titleEn;

  TaskModel copyWith({
    String? goalId,
    String? titleEn,
    String? titleAr,
    int? durationMinutes,
    TaskPriority? priority,
    TaskStatus? status,
    DateTime? scheduledDate,
  }) {
    return TaskModel(
      id: id,
      goalId: goalId ?? this.goalId,
      titleEn: titleEn ?? this.titleEn,
      titleAr: titleAr ?? this.titleAr,
      durationMinutes: durationMinutes ?? this.durationMinutes,
      priority: priority ?? this.priority,
      status: status ?? this.status,
      scheduledDate: scheduledDate ?? this.scheduledDate,
      createdAt: createdAt,
      isAutoGenerated: isAutoGenerated,
    );
  }
}
